language: node_js
node_js:
  - '8'
  - '6'
  - '4'

env:
  - WEBPACK_VERSION=1 EXTRACT_PLUGIN_VERSION=1
  - WEBPACK_VERSION=2 EXTRACT_PLUGIN_VERSION=2
  - WEBPACK_VERSION=3 EXTRACT_PLUGIN_VERSION=3.0.0-beta.3

install:
  - npm install
  - npm install webpack@$WEBPACK_VERSION extract-text-webpack-plugin@$EXTRACT_PLUGIN_VERSION || true
