version: 2
aliases:
  - &npm_install
    name: Install Dependencies
    command: npm ci
  - &restore_cache
    key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}

coverage: &coverage
  steps:
    - checkout
    - restore_cache: *restore_cache
    - run: *npm_install
    - run:
        name: Run unit tests.
        command: npm run ci:coverage
    - run:
        name: Submit Coverage
        command: bash <(curl -s https://codecov.io/bash)
        when: on_success

unit_tests: &unit_tests
  steps:
    - checkout
    - restore_cache: *restore_cache
    - run: *npm_install
    - run:
        name: Env Info
        command: |
          node --version
          npm --version
    - run:
        name: Run Tests
        command: |
          npm run ci:test
          echo "prev return code: $?"

jobs:
  analysis:
    docker:
      - image: rollupcabal/circleci-node-base:latest
    steps:
      - checkout
      - restore_cache: *restore_cache
      - run: *npm_install
      - run:
          name: Run Audit
          command: npm run security
      - run:
          name: Run Linting
          command: npm run ci:lint
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ./node_modules
  node-v10-latest:
    docker:
      - image: rollupcabal/circleci-node-v10:latest
    <<: *unit_tests
  node-v12-latest:
    docker:
      - image: rollupcabal/circleci-node-v12:latest
    <<: *unit_tests
  node-v14-latest:
    docker:
      - image: rollupcabal/circleci-node-v14:latest
    <<: *coverage

workflows:
  version: 2
  validate-test:
    jobs:
      - analysis:
          filters:
            tags:
              only: /.*/
      - node-v10-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
      - node-v12-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
      - node-v14-latest:
          requires:
            - analysis
          filters:
            tags:
              only: /.*/
